//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int patient_ID { get; set; }
        public string feedback1 { get; set; }
        public string result { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
